/**
 * Strongly-typed error codes for CodeSync error taxonomy.
 * Categorizes errors to ensure fail-closed handling without leaking internals.
 */
export enum ErrorCode {
  // Validation Errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
  SCHEMA_MISMATCH = "SCHEMA_MISMATCH",
  UNTRUSTED_PAYLOAD_REJECTED = "UNTRUSTED_PAYLOAD_REJECTED",

  // Configuration Errors
  CONFIGURATION_INVALID = "CONFIGURATION_INVALID",
  CONFIG_TRAVERSAL_DETECTED = "CONFIG_TRAVERSAL_DETECTED",
  CONFIG_MISSING_REQUIRED = "CONFIG_MISSING_REQUIRED",

  // Browser / Runtime Errors
  BROWSER_RUNTIME_UNAVAILABLE = "BROWSER_RUNTIME_UNAVAILABLE",
  STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE",
  CONTEXT_DISCONNECTED = "CONTEXT_DISCONNECTED",

  // Storage & Payload Errors
  STORAGE_ERROR = "STORAGE_ERROR",
  STORAGE_QUOTA_EXCEEDED = "STORAGE_QUOTA_EXCEEDED",
  STORAGE_CORRUPTED = "STORAGE_CORRUPTED",
  PAYLOAD_NOT_FOUND = "PAYLOAD_NOT_FOUND",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",

  // Messaging & Envelope Errors
  ENVELOPE_VALIDATION_FAILED = "ENVELOPE_VALIDATION_FAILED",
  REPLAY_ATTACK_DETECTED = "REPLAY_ATTACK_DETECTED",
  UNAUTHORIZED_SENDER = "UNAUTHORIZED_SENDER",

  // Queue, Concurrency & Fencing Errors
  QUEUE_FULL = "QUEUE_FULL",
  LEASE_ACQUISITION_FAILED = "LEASE_ACQUISITION_FAILED",
  LEASE_SUPERSEDED = "LEASE_SUPERSEDED",
  LEASE_MAX_LIFETIME_EXCEEDED = "LEASE_MAX_LIFETIME_EXCEEDED",
  STALE_WORKER_MUTATION = "STALE_WORKER_MUTATION",
  POISON_PILL_DETECTED = "POISON_PILL_DETECTED",
  WAL_RECOVERY_FAILED = "WAL_RECOVERY_FAILED",
  DEDUPLICATION_FAILED = "DEDUPLICATION_FAILED",

  // Architectural / Security Errors
  INVARIANT_VIOLATION = "INVARIANT_VIOLATION",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
  UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION",

  // Authentication & GitHub Lifecycle Errors
  GITHUB_AUTH_REQUIRED = "GITHUB_AUTH_REQUIRED",
  GITHUB_REFRESH_FAILED = "GITHUB_REFRESH_FAILED",
  GITHUB_DEVICE_CODE_EXPIRED = "GITHUB_DEVICE_CODE_EXPIRED",
  GITHUB_AUTHORIZATION_DENIED = "GITHUB_AUTHORIZATION_DENIED",
  GITHUB_DEVICE_FLOW_DISABLED = "GITHUB_DEVICE_FLOW_DISABLED",
  GITHUB_INCORRECT_DEVICE_CODE = "GITHUB_INCORRECT_DEVICE_CODE",
  GITHUB_RECONCILIATION_REQUIRED = "GITHUB_RECONCILIATION_REQUIRED",
  GITHUB_STALE_RESPONSE = "GITHUB_STALE_RESPONSE",

  // GitHub API & Repository Errors (Phase 1C.2)
  GITHUB_API_ERROR = "GITHUB_API_ERROR",
  GITHUB_RATE_LIMITED = "GITHUB_RATE_LIMITED",
  GITHUB_NOT_FOUND = "GITHUB_NOT_FOUND",
  GITHUB_CONFLICT = "GITHUB_CONFLICT",
  GITHUB_UNAUTHORIZED = "GITHUB_UNAUTHORIZED",
  GITHUB_FORBIDDEN = "GITHUB_FORBIDDEN",
  GITHUB_BRANCH_NOT_FOUND = "GITHUB_BRANCH_NOT_FOUND",
  GITHUB_REPOSITORY_NOT_FOUND = "GITHUB_REPOSITORY_NOT_FOUND",
  GITHUB_PATH_INVALID = "GITHUB_PATH_INVALID",
  GITHUB_TARGET_IS_DIRECTORY = "GITHUB_TARGET_IS_DIRECTORY",
  GITHUB_UNSUPPORTED_OBJECT_TYPE = "GITHUB_UNSUPPORTED_OBJECT_TYPE",
  GITHUB_PAYLOAD_TOO_LARGE = "GITHUB_PAYLOAD_TOO_LARGE",
  GITHUB_WRITE_OUTCOME_UNKNOWN = "GITHUB_WRITE_OUTCOME_UNKNOWN",
  GITHUB_VERIFICATION_FAILED = "GITHUB_VERIFICATION_FAILED",

  // Path Security & Template Errors (Phase 1C.2)
  PATH_TRAVERSAL_DETECTED = "PATH_TRAVERSAL_DETECTED",
  PATH_INVALID_CHARACTER = "PATH_INVALID_CHARACTER",
  PATH_SEGMENT_TOO_LONG = "PATH_SEGMENT_TOO_LONG",
  PATH_TOTAL_TOO_LONG = "PATH_TOTAL_TOO_LONG",
  PATH_EMPTY_SEGMENT = "PATH_EMPTY_SEGMENT",
  PATH_ABSOLUTE_REJECTED = "PATH_ABSOLUTE_REJECTED",
  PATH_RESERVED_NAME = "PATH_RESERVED_NAME",
  PATH_BOUNDARY_VIOLATION = "PATH_BOUNDARY_VIOLATION",
  TEMPLATE_UNKNOWN_VARIABLE = "TEMPLATE_UNKNOWN_VARIABLE",
  TEMPLATE_MALFORMED = "TEMPLATE_MALFORMED",
  TEMPLATE_MISSING_VALUE = "TEMPLATE_MISSING_VALUE",

  // Platform Adapter & Extraction Errors (Phase 1C.3)
  ADAPTER_NOT_APPLICABLE = "ADAPTER_NOT_APPLICABLE",
  SUBMISSION_NOT_DETECTED = "SUBMISSION_NOT_DETECTED",
  STATUS_UNKNOWN = "STATUS_UNKNOWN",
  SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND",
  SOURCE_INVALID = "SOURCE_INVALID",
  METADATA_INVALID = "METADATA_INVALID",
  ORIGIN_REJECTED = "ORIGIN_REJECTED",
  EXTRACTION_FAILED = "EXTRACTION_FAILED",
  UNSUPPORTED_PLATFORM_STATE = "UNSUPPORTED_PLATFORM_STATE",
  ADAPTER_ALREADY_REGISTERED = "ADAPTER_ALREADY_REGISTERED",
  ADAPTER_REGISTRATION_INVALID = "ADAPTER_REGISTRATION_INVALID",
}
